variables:
  CI_DEBUG_SERVICES: "true"

before_script:
  - apk update
  - apk --no-cache add py3-pip python3 curl gettext
  - python3 -m venv $HOME/.venv
  - export PATH=$HOME/.venv/bin:$PATH
  - pip3 install pyyaml
  - curl -O https://raw.githubusercontent.com/FredHutch/swarm-build-helper/main/build_helper.py 
  # below is from https://stackoverflow.com/a/65810302/470769
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - set -x

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t sc-registry.fredhutch.org/ichorcurate:test .
    - docker push sc-registry.fredhutch.org/ichorcurate:test

test:
  stage: test
  services: 
    - name: sc-registry.fredhutch.org/ichorcurate:test
      alias: ichorcurate
  script:
    - sleep 15 && curl -sI  http://ichorcurate:8501  |head -1|grep -q "200 OK"

deploy:
  stage: deploy
  only:
    refs:
        - main
  script:
    - docker tag sc-registry.fredhutch.org/ichorcurate:test sc-registry.fredhutch.org/ichorcurate:latest
    - docker push sc-registry.fredhutch.org/ichorcurate:latest
    - sleep 15
    - echo $SC_SWARM_CICD_SSH_KEY | base64 -d > ./sc_swarm_cicd_ssh_key
    - chmod 0400 ./sc_swarm_cicd_ssh_key
    - cat docker-compose.yml | envsubst | python3 build_helper.py - | ssh -i ./sc_swarm_cicd_ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@sc-swarm-mgr.fhcrc.org docker stack deploy --with-registry-auth -c - ichorcurate